CREATE TABLE [dbo].[Session]
(
	[SessionId] INT IDENTITY(1,1) NOT NULL,
	[EventId] INT NOT NULL,
	[SessionName] VARCHAR(50) NOT NULL,
	[Description] VARCHAR(MAX) NULL,
	[HostName] VARCHAR(50) NOT NULL,
	[StartTime] DATETIME NOT NULL,
	[EndTime] DATETIME NOT NULL,
	[MaxCount] INT NULL
CONSTRAINT [PK_Session] PRIMARY KEY CLUSTERED   
(  
    [SessionId] ASC  
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  
) ON [PRIMARY]  
GO
ALTER TABLE [dbo].[Event]  ADD  CONSTRAINT [FK_Event_Session] FOREIGN KEY([EventId])
REFERENCES [dbo].[Event] ([EventId])
GO