CREATE TABLE [dbo].[User]
(
	[UserId] INT IDENTITY(1,1) NOT NULL,
	[UserName] VARCHAR(200) NOT NULL,
	[Password] VARCHAR(200) NOT NULL,
	[IsActive] BIT NOT NULL
CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED   
(  
    [UserId] ASC  
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]  
) ON [PRIMARY]  
Go