export const signIn = 'Account/SignIn'
export const getEvents = 'SessionTask/GetEvents'
export const saveEvent = 'SessionTask/SaveEvent'
export const getSessions = 'SessionTask/GetSessions'
export const saveSession = 'SessionTask/SaveSession'
export const approveAttendees = 'SessionTask/ApproveAttendees'
export const enrollToSession = 'SessionTask/EnrollToSession'
export const getSessionAttendees = 'SessionTask/GetSessionAttendees'